### ISSUE TITLE
osf_upload docs typo

### ISSUE THREAD

**Issue by norlab** [ropensci/osfr#116]
I believe (based on my use of the osf_upload function) that there is a typo in the docs. Line 76 of gives the example code: 
`osf_upload("iris.csv", overwrite = TRUE) %>%`

but I believe it should be:
`osf_upload("iris.csv", conflicts = "overwrite") %>%`

Thank you for this package it has been extremely helpful for automating processes in my lab!

**Comment by aaronwolen** [comment]
You're totally right. Thanks for reporting!

**Comment by aaronwolen** [comment]
Fixed in v0.2.7. Thanks!
