### ISSUE TITLE
Errors in running the package

### ISSUE THREAD

**Issue by mmkamso** [ropensci/osfr#124]
Hi Aaron,

I have been trying to install your package on R version 3.5 but keep running into some errors. Below is the message i get when i try to install the package. Thank you.

* installing *source* package ‘rlang’ ...
** package ‘rlang’ successfully unpacked and MD5 sums checked
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘rlang’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rlang’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rlang’
Error: Failed to install 'osfr' from GitHub:
  (converted from warning) installation of package ‘rlang’ had non-zero exit status
> library(osfr)
Error: package or namespace load failed for ‘osfr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘fs’ 1.2.7 is being loaded, but >= 1.3.0 is required

**Comment by aaronwolen** [comment]
Did you get it working @mmkamso?

**Comment by mmkamso** [comment]
Yes I did get it ti work by updating the R software and Rstudio. Thank you.
