### ISSUE TITLE
Overwrite argument not working in osf_upload function

### ISSUE THREAD

**Issue by mmkamso** [ropensci/osfr#125]
Hi Aaron,

Please the overwrite argument is not working in the osf_upload function suggesting unused argument, could you have a look? And Thank you for this package.

# Create an example file to upload to our example project
write.csv(iris, file = "iris.csv")
project <- osf_create_project("Flower Data")

# Upload the first version
osf_upload(project,"iris.csv")

# Modify the data file, upload version 2, and view it on OSF
write.csv(subset(iris, Species != "setosa"), file = "iris.csv")
project %>%
  osf_upload("iris.csv", overwrite = TRUE) %>%
  osf_open()

Error in osf_upload(., "iris.csv", overwrite = TRUE) : 
  unused argument (overwrite = TRUE)

**Comment by timriffe** [comment]
Try it with `conflicts = "overwrite"` rather than `overwrite = TRUE`.

```
write.csv(iris, file = "iris.csv")
project <- osf_create_project("Flower Data")
osf_upload(project,"iris.csv")
write.csv(subset(iris, Species != "setosa"), file = "iris.csv")
project %>%
  osf_upload("iris.csv", conflicts = "overwrite") %>%
  osf_open()
```

This seems to work. Or did I get that wrong? I'm however, also having issues with this in a different context, but struggling to make a handy reproducible example...

**Comment by aaronwolen** [comment]
Thanks for chiming in @timriffe. This is indeed the fix @mmkamso needs.

Let me know if you need help with the other issue you referenced.
