### ISSUE TITLE
File won't overwrite in osf_upload

### ISSUE THREAD

**Issue by befriendabacterium** [ropensci/osfr#127]
Hi there,

Thanks for this great package. I'm having trouble overwriting a file in OSF:

osf_upload(project, 'data.csv', conflicts="overwrite")

doesn't work. I get the error:

'Error: Cannot complete action: file or folder "data.csv" already exists in this location
       HTTP status code 409.'

I have authenticated with osf_auth and can upload files, just not overwrite. Any ideas?

Thanks
Matt

**Comment by befriendabacterium** [comment]
Ah yes - it's the latter. Thanks! Have managed a workaround now by removing then re-uploading!

**Comment by aaronwolen** [comment]
Thanks!
