### ISSUE TITLE
osf_rm: 'check' option doesn't work

### ISSUE THREAD

**Issue by befriendabacterium** [ropensci/osfr#128]
When i enter check = F I get:

Error: The specified file is no longer available.

**Comment by aaronwolen** [comment]
Could you post a reproducible example? This seems to work okay for me:

```r
proj <- osf_create_project("osfr issue 138", public = TRUE)

write.csv(mtcars, file = "mtcars.csv")
mtcars_file <- osf_upload(proj, "mtcars.csv")

osf_rm(mtcars_file, check = FALSE)
```

**Comment by befriendabacterium** [comment]
Sorry, it seems to be working now and I can't reproduce my own issue! Doh! Perhaps it was to do with check = F not check = FALSE but that doesn't make sense...hmmm

**Comment by aaronwolen** [comment]
No problem. I'm closing for now but feel free to reopen if you come across an example where this fails.
