### ISSUE TITLE
Missing some files from osfr::osf_ls_files()

### ISSUE THREAD

**Issue by JMankewitz** [ropensci/osfr#135]
Hello!

We have a public project at the address https://osf.io/pr6wu/, which has multiple subfolders (21!) which we need to interface with osfr::osf_download() and osfr::osf_upload()

However, when we run `osfr::osf_retrieve_node("pr6wu") %>% osfr::osf_ls_files()` we only get 10 of our 21 subfolders, so we can't access the other 11.

Any help would be great!

**Comment by JMankewitz** [comment]
Seems like there needs to be some page handling - see bottom of page here: https://api.osf.io/v2/nodes/pr6wu/files/osfstorage/ (there are 3 pages, with max 10 files each)

**Comment by aaronwolen** [comment]
Hi @JMankewitz, thanks for posting. You can set `osf_ls_files()`'s `n_max` argument to return more than 10 results. Let me know if that helps.

**Comment by JMankewitz** [comment]
Ah perfect, we'd missed that. Thanks !!

**Comment by aaronwolen** [comment]
Awesome. I'll close this but feel free to re-open if you run into other issues.
